name: states_and_capitals
description: "A simple package for getting the states/regions and local governments in a country"
version: 0.0.1
repository: https://github.com/Tinalexman/states_and_capital.git

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: