import 'package:states_and_capitals/data/lga.dart';
import 'package:states_and_capitals/data/state.dart';

const State oromia = State(
  stateId: 0,
  name: "Oromia",
  capital: "Finfinne",
  motto: "",
  numberOfLocalGovernments: 321,
);

const List<LGA> oromiaLocalGovernments = [
  LGA(name: "Aminya"),
  LGA(name: "Aseko"),
  LGA(name: "Asella Town"),
  LGA(name: "Bale"),
  LGA(name: "Gasegar"),
  LGA(name: "Batu Dugda"),
  LGA(name: "Chole"),
  LGA(name: "Digeluna"),
  LGA(name: "Tijo"),
  LGA(name: "Diksis"),
  LGA(name: "Dodota"),
  LGA(name: "Enkelo Wabe"),
  LGA(name: "Gololcha"),
  LGA(name: "Guna"),
  LGA(name: "Hitosa"),
  LGA(name: "Jeju"),
  LGA(name: "Limuna Bilbilo"),
  LGA(name: "Lude Hitosa"),
  LGA(name: "Merti"),
  LGA(name: "Munesa"),
  LGA(name: "Robe"),
  LGA(name: "Seru"),
  LGA(name: "Sire"),
  LGA(name: "Sherka"),
  LGA(name: "Sude"),
  LGA(name: "Tena"),
  LGA(name: "Tiyo"),
  LGA(name: "Agarfa"),
  LGA(name: "Robe Town"),
  LGA(name: "Berbere"),
  LGA(name: "Dawe Kachen"),
  LGA(name: "Dawe Serara"),
  LGA(name: "Delo Menna"),
  LGA(name: "Dinsho"),
  LGA(name: "Gasera"),
  LGA(name: "Ginir"),
  LGA(name: "Goba"),
  LGA(name: "Goba Town"),
  LGA(name: "Gololcha"),
  LGA(name: "Goro"),
  LGA(name: "Guradamole"),
  LGA(name: "Legehida"),
  LGA(name: "Raytu"),
  LGA(name: "Seweyna"),
  LGA(name: "Sinana"),
  LGA(name: "Arero"),
  LGA(name: "Dillo"),
  LGA(name: "Dire"),
  LGA(name: "Gomole"),
  LGA(name: "Miyu"),
  LGA(name: "Moyale"),
  LGA(name: "Teltele"),
  LGA(name: "Yabelo"),
  LGA(name: "Bedele Zuria"),
  LGA(name: "Bedele Town"),
  LGA(name: "Borecha"),
  LGA(name: "Chewaka"),
  LGA(name: "Chora"),
  LGA(name: "Dabo Hana"),
  LGA(name: "Dega"),
  LGA(name: "Didessa"),
  LGA(name: "Gechi"),
  LGA(name: "Mako"),
  LGA(name: "Guji woreda"),
  LGA(name: "Gumi Eldalo"),
  LGA(name: "Harena Buluk"),
  LGA(name: "Liben"),
  LGA(name: "Meda Welabu"),
  LGA(name: "Moyale"),
  LGA(name: "Moyale woreda"),
  LGA(name: "Negele Borana"),
  LGA(name: "Oborso"),
  LGA(name: "Wachile"),
  LGA(name: "Babile"),
  LGA(name: "Badeno"),
  LGA(name: "Chinaksen"),
  LGA(name: "Dadar"),
  LGA(name: "Fedis"),
  LGA(name: "Girawa"),
  LGA(name: "Gola Oda"),
  LGA(name: ""),
  LGA(name: "Goro Gutu"),
  LGA(name: "Gursum"),
  LGA(name: "Haro Maya"),
  LGA(name: "Jarso"),
  LGA(name: "Kersa"),
  LGA(name: "Kombolcha"),
  LGA(name: "Kurfa Chele"),
  LGA(name: "Malka Balo"),
  LGA(name: "Meyumuluke"),
  LGA(name: "Meta"),
  LGA(name: "Midega"),
  LGA(name: "Tola"),
  LGA(name: "Ada'a Adami Tullu"),
  LGA(name: "Jido Kombolcha"),
  LGA(name: "Batu town"),
  LGA(name: "Bishoftu"),
  LGA(name: "Bora"),
  LGA(name: "Boset"),
  LGA(name: "Dugda"),
  LGA(name: "Fentale"),
  LGA(name: "Gimbichu"),
  LGA(name: "Liben"),
  LGA(name: "Lome"),
  LGA(name: "Nannawa Adama"),
  LGA(name: "Bonaya Boshe"),
  LGA(name: "Diga"),
  LGA(name: "Gida Kiremu"),
  LGA(name: "Gobu Seyo"),
  LGA(name: "Gudeya Bila"),
  LGA(name: "Guto Gida"),
  LGA(name: "Haro Limmu"),
  LGA(name: "Ibantu"),
  LGA(name: "Jimma"),
  LGA(name: "Arjo"),
  LGA(name: "Leka"),
  LGA(name: "Dulecha"),
  LGA(name: "Limmu"),
  LGA(name: "Nekemte"),
  LGA(name: "Nunu Kumba"),
  LGA(name: "Sasiga"),
  LGA(name: "Sibu Sire"),
  LGA(name: "Wama Hagalo"),
  LGA(name: "Wayu"),
  LGA(name: "Tuka"),
  LGA(name: "Adola"),
  LGA(name: "Adola Town"),
  LGA(name: "Ana Sora"),
  LGA(name: "Bore"),
  LGA(name: "Dima"),
  LGA(name: "Girja"),
  LGA(name: "Harenfema"),
  LGA(name: "Odo Shakiso"),
  LGA(name: "Uraga"),
  LGA(name: "Wadera"),
  LGA(name: "Abay Chomen"),
  LGA(name: "Abe Dongoro"),
  LGA(name: "Amuru"),
  LGA(name: "Guduru"),
  LGA(name: "Hababo Guduru"),
  LGA(name: "Horo"),
  LGA(name: "Jardega"),
  LGA(name: "Jarte"),
  LGA(name: "Jimma Genete"),
  LGA(name: "Jimma Rare"),
  LGA(name: "Shambu Town"),
  LGA(name: "I"),
  LGA(name: "Ale"),
  LGA(name: "Alge Sache"),
  LGA(name: "Bicho"),
  LGA(name: "Bilo Nopha"),
  LGA(name: "Bure"),
  LGA(name: "Darimu"),
  LGA(name: "Didu"),
  LGA(name: "Doreni"),
  LGA(name: "Huka"),
  LGA(name: "Halu"),
  LGA(name: "Hurumu"),
  LGA(name: "Metu Zuria"),
  LGA(name: "Metu Town"),
  LGA(name: "Nono Sele"),
  LGA(name: "Supena Sodo"),
  LGA(name: "Yayu"),
  LGA(name: "Agaro Town"),
  LGA(name: "Chora Botor"),
  LGA(name: "Dedo"),
  LGA(name: "Gera"),
  LGA(name: "Gomma"),
  LGA(name: "Guma"),
  LGA(name: "Kersa "),
  LGA(name: "Limmu Sakka"),
  LGA(name: "Limmu Kosa"),
  LGA(name: "Mana"),
  LGA(name: "Omo"),
  LGA(name: "Nada"),
  LGA(name: "Seka"),
  LGA(name: "Chekorsa"),
  LGA(name: "Setema"),
  LGA(name: "Shebe"),
  LGA(name: "Senbo"),
  LGA(name: "Sigmo"),
  LGA(name: "Sokoru"),
  LGA(name: "Tiro Afeta"),
  LGA(name: "Anfillo"),
  LGA(name: "Dale Sedi"),
  LGA(name: "Dale Wabera"),
  LGA(name: "Dembidolo Town"),
  LGA(name: "Gawo Kebe"),
  LGA(name: "Gidami"),
  LGA(name: "Hawa Gelan"),
  LGA(name: "Jimma Horo"),
  LGA(name: "Lalo Kile"),
  LGA(name: "Sayo"),
  LGA(name: "Yemalogi"),
  LGA(name: "Welele"),
  LGA(name: "Abichu"),
  LGA(name: "Aleltu"),
  LGA(name: "Degem"),
  LGA(name: "Dera"),
  LGA(name: "Fiche Town"),
  LGA(name: "Gerar Jarso"),
  LGA(name: "Hidabu"),
  LGA(name: "Abote"),
  LGA(name: "Jido"),
  LGA(name: "Kembibit"),
  LGA(name: "Kuyu"),
  LGA(name: "Liban"),
  LGA(name: "Wara Jarso"),
  LGA(name: "Wuchale"),
  LGA(name: "Yaya"),
  LGA(name: "Gulele"),
  LGA(name: "Amaya"),
  LGA(name: "Becho"),
  LGA(name: "Dawo"),
  LGA(name: "Elu"),
  LGA(name: "Goro"),
  LGA(name: "Kersana"),
  LGA(name: "Malima"),
  LGA(name: "Seden Sodo"),
  LGA(name: "Sodo Dacha"),
  LGA(name: "Tole"),
  LGA(name: "Waliso"),
  LGA(name: "Waliso Town"),
  LGA(name: "Wanchi"),
  LGA(name: "Adaba"),
  LGA(name: "Arsi Negele"),
  LGA(name: "Dodola"),
  LGA(name: "Gedeb"),
  LGA(name: "Asasa"),
  LGA(name: "Kofele"),
  LGA(name: "Kokosa"),
  LGA(name: "Kore"),
  LGA(name: "Naannawa Shashamane"),
  LGA(name: "Nensebo"),
  LGA(name: "Seraro"),
  LGA(name: "Shala"),
  LGA(name: "Shashamane Town"),
  LGA(name: "Abaya"),
  LGA(name: "Birbirsa"),
  LGA(name: "Kojowa"),
  LGA(name: "Bule Hora"),
  LGA(name: "Bule Hora woreda"),
  LGA(name: ""),
  LGA(name: "Dugda Dawa"),
  LGA(name: "Hambela"),
  LGA(name: "Wamena"),
  LGA(name: "Kercha"),
  LGA(name: "Gelana"),
  LGA(name: "Malka Soda"),
  LGA(name: "Suro"),
  LGA(name: "Barguda"),
  LGA(name: "Badessa Town"),
  LGA(name: "Boke"),
  LGA(name: "Char char"),
  LGA(name: "Chiro Town"),
  LGA(name: "Daru labu"),
  LGA(name: "Doba"),
  LGA(name: "Gamachis"),
  LGA(name: "Guba"),
  LGA(name: "Koricha"),
  LGA(name: "Habro"),
  LGA(name: "Kuni"),
  LGA(name: "Masela"),
  LGA(name: "Mieso"),
  LGA(name: "Nannawa Chiro"),
  LGA(name: "Tulo"),
  LGA(name: "Abuna Ginde"),
  LGA(name: "Beret"),
  LGA(name: "Adda Berga"),
  LGA(name: "Ambo Town"),
  LGA(name: "Bako Tibe"),
  LGA(name: "Cheliya"),
  LGA(name: "Dano"),
  LGA(name: "Dendi"),
  LGA(name: "Dire Enchini"),
  LGA(name: "Ejerie"),
  LGA(name: "Elfata"),
  LGA(name: "Ginde Beret"),
  LGA(name: "Gurraacha Enchini"),
  LGA(name: "Jeldu"),
  LGA(name: "Jibat"),
  LGA(name: ""),
  LGA(name: "Meta Robi"),
  LGA(name: "Midakegn"),
  LGA(name: "Naannawa Ambo"),
  LGA(name: "Nono"),
  LGA(name: "Toke"),
  LGA(name: "Kutaye"),
  LGA(name: "Ayra"),
  LGA(name: "Babo"),
  LGA(name: "Gambela"),
  LGA(name: "Begi"),
  LGA(name: "Boji Chokorsa"),
  LGA(name: "Boji Dirmaji"),
  LGA(name: "Genji"),
  LGA(name: "Gimbi"),
  LGA(name: "Gimbi Town"),
  LGA(name: "Guliso"),
  LGA(name: "Haru"),
  LGA(name: "Homa"),
  LGA(name: "Jarso"),
  LGA(name: "Kondala"),
  LGA(name: "Kiltu"),
  LGA(name: "Kara"),
  LGA(name: "Lalo Asabi"),
  LGA(name: "Mana Sibu"),
  LGA(name: "Nejo"),
  LGA(name: "Nole Kaba"),
  LGA(name: "Sayo Nole"),
  LGA(name: "Yubdo"),
  LGA(name: "Akaki"),
  LGA(name: "Bereh"),
  LGA(name: "Burayu Town"),
  LGA(name: "Holeta Town"),
  LGA(name: "Koye Feche"),
  LGA(name: "Mulo"),
  LGA(name: "Sebeta"),
  LGA(name: "Hawas"),
  LGA(name: "Sendafa Town"),
  LGA(name: "Sululta"),
  LGA(name: "Walmara")
];

void main() {
  // Map to count occurrences
  Map<String, int> countMap = {};

  // Populate the map with string counts
  for (var item in oromiaLocalGovernments) {
    countMap[item.name] = (countMap[item.name] ?? 0) + 1;
  }

  // Find duplicates (values with count > 1)
  List<String> duplicates = [];
  countMap.forEach((key, value) {
    if (value > 1) {
      duplicates.add(key);
    }
  });
  print(
      "The total oromiaLocalGovernments is: ${oromiaLocalGovernments.length}");
  // Print the duplicates
  if (duplicates.isNotEmpty) {
    print("Duplicates found: ${duplicates.join(', ')}");
  } else {
    print("No duplicates found");
  }
}
